[package]
name = "TraceLock-epbf"
version = "0.1.0"
edition.workspace = true

license.workspace = true

[dependencies]
TraceLock_epbf_common = { package = "TraceLock-epbf-common", path = "../TraceLock_epbf_common", features = ["user"] }
TraceLock-core = { path = "../../TraceLock-core" }

anyhow = { workspace = true, default-features = true }
aya = { workspace = true }
aya-log = { workspace = true }
env_logger = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
] }

[build-dependencies]
anyhow = { workspace = true }
aya-build = { workspace = true }
cargo_metadata = { workspace = true }
TraceLock_epbf_ebpf = { package = "TraceLock-epbf-ebpf", path = "../TraceLock_epbf_ebpf" }

[[bin]]
name = "TraceLock-epbf"
path = "src/main.rs"